### ISSUE TITLE
Doesnt show anything

### ISSUE THREAD

**Issue by kordzadeh** [snowio/magento2-average-product-rating#6]
Hi,
i just installed your module and it installed. but problem is that it doesnt show anything... what should i do?
installed it on magento 2.1.8 luma theme.
should i do anything?

**Comment by darryla** [comment]
This module is an extension to the Magento API, it extends the data available through product GET API calls. It does not change the function of any theme.

**Comment by kordzadeh** [comment]
Thanks for your kind response

Pegah Kordzadeh
ETC and RFID technical manager of EhSAA Corp.
Web Designer of vista group
